 # ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://reno-expert.be/renovatie_a_tot_z
baseurl:
title: "Reno Expert: Voor uw renovatie van A tot Z"
email:
author:
description: "Uw woning van top tot teen renoveren? Reno Expert pakt alle opknapwerken aan, in en rond de provincie Antwerpen. Van Sanitair, elektro, verwarming tot domotica."
port: 4002


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# ---------------------------------------------------------------------------- #
#    1) copy plugins to config:
#  - jekyll-seo-tag
#  - jekyll-sitemap
#
#    2) make gemfile in root and add the below:
#   source 'https://rubygems.org'   (this is important for bundle install)
#   gem 'jekyll-seo-tag'
#   gem 'jekyll-sitemap'
#
#   3)  In command of project type: "bundle install" & then "bundle update"
# ---------------------------------------------------------------------------- #


# Build settings
markdown: kramdown
permalink: pretty
